apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
    name: mysql
    namespace: admin
spec:
  releaseName: mysql
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mysql
    version: 1.6.2
  values:
    imageTag: "5.7.29"
    persistence:
      enabled: false